// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: datamask.proto

package name

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 注册请求
type UserInitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户名
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 手机号
	Mobile int64 `protobuf:"varint,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 密码
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *UserInitReq) Reset() {
	*x = UserInitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamask_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInitReq) ProtoMessage() {}

func (x *UserInitReq) ProtoReflect() protoreflect.Message {
	mi := &file_datamask_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInitReq.ProtoReflect.Descriptor instead.
func (*UserInitReq) Descriptor() ([]byte, []int) {
	return file_datamask_proto_rawDescGZIP(), []int{0}
}

func (x *UserInitReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInitReq) GetMobile() int64 {
	if x != nil {
		return x.Mobile
	}
	return 0
}

func (x *UserInitReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 用户登陆请求
type UserLogReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户名
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 手机号
	Mobile int64 `protobuf:"varint,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 密码
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *UserLogReq) Reset() {
	*x = UserLogReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamask_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogReq) ProtoMessage() {}

func (x *UserLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_datamask_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogReq.ProtoReflect.Descriptor instead.
func (*UserLogReq) Descriptor() ([]byte, []int) {
	return file_datamask_proto_rawDescGZIP(), []int{1}
}

func (x *UserLogReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserLogReq) GetMobile() int64 {
	if x != nil {
		return x.Mobile
	}
	return 0
}

func (x *UserLogReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 文件上传请求
type FileUpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户名
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 手机号
	Mobile int64 `protobuf:"varint,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 密码
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *FileUpReq) Reset() {
	*x = FileUpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamask_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUpReq) ProtoMessage() {}

func (x *FileUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_datamask_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUpReq.ProtoReflect.Descriptor instead.
func (*FileUpReq) Descriptor() ([]byte, []int) {
	return file_datamask_proto_rawDescGZIP(), []int{2}
}

func (x *FileUpReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileUpReq) GetMobile() int64 {
	if x != nil {
		return x.Mobile
	}
	return 0
}

func (x *FileUpReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 通用响应
type NormalResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 状态码  (0正常 其余均为异常状态)
	StatusCode bool `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// 其余信息
	OtherMessage string `protobuf:"bytes,2,opt,name=other_message,json=otherMessage,proto3" json:"other_message,omitempty"`
}

func (x *NormalResp) Reset() {
	*x = NormalResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamask_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NormalResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalResp) ProtoMessage() {}

func (x *NormalResp) ProtoReflect() protoreflect.Message {
	mi := &file_datamask_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalResp.ProtoReflect.Descriptor instead.
func (*NormalResp) Descriptor() ([]byte, []int) {
	return file_datamask_proto_rawDescGZIP(), []int{3}
}

func (x *NormalResp) GetStatusCode() bool {
	if x != nil {
		return x.StatusCode
	}
	return false
}

func (x *NormalResp) GetOtherMessage() string {
	if x != nil {
		return x.OtherMessage
	}
	return ""
}

// 通用请求
type NormalReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NormalReq) Reset() {
	*x = NormalReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamask_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NormalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalReq) ProtoMessage() {}

func (x *NormalReq) ProtoReflect() protoreflect.Message {
	mi := &file_datamask_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalReq.ProtoReflect.Descriptor instead.
func (*NormalReq) Descriptor() ([]byte, []int) {
	return file_datamask_proto_rawDescGZIP(), []int{4}
}

// 历史记录响应
type HistoryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 历史记录数量
	HistoryNumber int64 `protobuf:"varint,1,opt,name=history_number,json=historyNumber,proto3" json:"history_number,omitempty"`
	// 其余信息
	OtherMessage string `protobuf:"bytes,2,opt,name=other_message,json=otherMessage,proto3" json:"other_message,omitempty"`
}

func (x *HistoryResp) Reset() {
	*x = HistoryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamask_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResp) ProtoMessage() {}

func (x *HistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_datamask_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResp.ProtoReflect.Descriptor instead.
func (*HistoryResp) Descriptor() ([]byte, []int) {
	return file_datamask_proto_rawDescGZIP(), []int{5}
}

func (x *HistoryResp) GetHistoryNumber() int64 {
	if x != nil {
		return x.HistoryNumber
	}
	return 0
}

func (x *HistoryResp) GetOtherMessage() string {
	if x != nil {
		return x.OtherMessage
	}
	return ""
}

var File_datamask_proto protoreflect.FileDescriptor

var file_datamask_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x55, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x69, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62,
	0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x54, 0x0a,
	0x0a, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x53, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x52, 0x0a, 0x0a, 0x4e, 0x6f, 0x72, 0x6d,
	0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x74, 0x68, 0x65, 0x72,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x6f, 0x74, 0x68, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0b, 0x0a, 0x09,
	0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x22, 0x59, 0x0a, 0x0b, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x0e, 0x68, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0d, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x23, 0x0a, 0x0d, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0xcf, 0x01, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x73,
	0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x69, 0x74, 0x12, 0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4e,
	0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x09, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x10, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2b, 0x0a, 0x06, 0x46, 0x69,
	0x6c, 0x65, 0x55, 0x70, 0x12, 0x0f, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x55, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4e, 0x6f, 0x72,
	0x6d, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x07, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x12, 0x0f, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c,
	0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x61, 0x74, 0x68, 0x3b, 0x6e,
	0x61, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_datamask_proto_rawDescOnce sync.Once
	file_datamask_proto_rawDescData = file_datamask_proto_rawDesc
)

func file_datamask_proto_rawDescGZIP() []byte {
	file_datamask_proto_rawDescOnce.Do(func() {
		file_datamask_proto_rawDescData = protoimpl.X.CompressGZIP(file_datamask_proto_rawDescData)
	})
	return file_datamask_proto_rawDescData
}

var file_datamask_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_datamask_proto_goTypes = []interface{}{
	(*UserInitReq)(nil), // 0: main.UserInitReq
	(*UserLogReq)(nil),  // 1: main.UserLogReq
	(*FileUpReq)(nil),   // 2: main.FileUpReq
	(*NormalResp)(nil),  // 3: main.NormalResp
	(*NormalReq)(nil),   // 4: main.NormalReq
	(*HistoryResp)(nil), // 5: main.HistoryResp
}
var file_datamask_proto_depIdxs = []int32{
	0, // 0: main.DataMaskService.UserInit:input_type -> main.UserInitReq
	1, // 1: main.DataMaskService.UserLogin:input_type -> main.UserLogReq
	2, // 2: main.DataMaskService.FileUp:input_type -> main.FileUpReq
	4, // 3: main.DataMaskService.History:input_type -> main.NormalReq
	3, // 4: main.DataMaskService.UserInit:output_type -> main.NormalResp
	3, // 5: main.DataMaskService.UserLogin:output_type -> main.NormalResp
	3, // 6: main.DataMaskService.FileUp:output_type -> main.NormalResp
	5, // 7: main.DataMaskService.History:output_type -> main.HistoryResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_datamask_proto_init() }
func file_datamask_proto_init() {
	if File_datamask_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_datamask_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamask_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLogReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamask_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileUpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamask_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NormalResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamask_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NormalReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamask_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistoryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_datamask_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datamask_proto_goTypes,
		DependencyIndexes: file_datamask_proto_depIdxs,
		MessageInfos:      file_datamask_proto_msgTypes,
	}.Build()
	File_datamask_proto = out.File
	file_datamask_proto_rawDesc = nil
	file_datamask_proto_goTypes = nil
	file_datamask_proto_depIdxs = nil
}
